name: Deploy and Execute Script
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}
    - name: Clear Remote Directory Before Copying
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY_PRIVATE }}
        script: |
          REMOTE_DIRECTORY="${{ vars.DEFAULT_PATH }}${{ vars.PROJECT_PATH }}"
          if [ -d "$REMOTE_DIRECTORY" ]; then
            echo "Удаление старых файлов в $REMOTE_DIRECTORY..."
            rm -rf $REMOTE_DIRECTORY/*
          else
            echo "Создание директории $REMOTE_DIRECTORY..."
            mkdir -p $REMOTE_DIRECTORY
          fi
    - name: Copy Directory to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY_PRIVATE }}
        source: "./*"
        target: "${{ vars.DEFAULT_PATH }}${{ vars.PROJECT_PATH }}"
        strip_components: 0
        overwrite: true
    - name: Execute Script on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY_PRIVATE }}
        script: |
          REMOTE_DIRECTORY="${{ vars.DEFAULT_PATH }}${{ vars.PROJECT_PATH }}"
          if [ ! -d "$REMOTE_DIRECTORY" ]; then
            echo "Директория не найдена, что-то пошло не так."
          else
            echo "Директория успешно скопирована. Запуск скрипта..."
            chmod +x $REMOTE_DIRECTORY/main.sh
            $REMOTE_DIRECTORY/main.sh $REMOTE_DIRECTORY/websites.yaml
          fi
        
